### ISSUE TITLE
[1.8.9] Crash on startup with the 1.8.9 verison

### ISSUE THREAD

**Issue by zacklmoore** [Team-RTG/1.8.9-Realistic-Terrain-Generation#29]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.4.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  MalisisCorePlugin (malisiscore-1.8.9-2.0.1.jar)
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.4.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/28/16 7:26 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: flower_island
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: flower_island
	at rtg.world.biome.realistic.biomesoplenty.RealisticBiomeBOPBase.addBiomes(RealisticBiomeBOPBase.java:110)
	at rtg.RTG.fmlLifeCycle(RTG.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 554240704 bytes (528 MB) / 1482772480 bytes (1414 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1762 Optifine OptiFine_1.8.9_HD_U_H4 87 mods loaded, 87 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1762.jar) 
	UCHIJ	Forge{11.15.1.1762} [Minecraft Forge] (forge-1.8.9-11.15.1.1762.jar) 
	UCHIJ	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJ	Thaumcraft{5.1.6} [Thaumcraft] (Thaumcraft-1.8.9-5.1.6.jar) 
	UCHIJ	tknowledge{0.2.0} [Thaumaturgical Knowledge] (1.8.9 - Thaumaturgical Knowledge-0.2.jar) 
	UCHIJ	securitycraft{v1.8.1} [SecurityCraft] ([1.8.8] SecurityCraft v1.8.1.jar) 
	UCHIJ	AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar) 
	UCHIJ	ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
	UCHIJ	AutoSapling{1.0} [Auto Sapling] (AutoSapling 1.2 MC1.8.9.jar) 
	UCHIJ	bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
	UCHIJ	bdlib{1.10.0.23} [BD Lib] (bdlib-1.10.0.23-mc1.8.9.jar) 
	UCHIJ	BetterFoliage{2.0.4} [Better Foliage] (BetterFoliage-MC1.8.x-2.0.4.jar) 
	UCHIJ	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1896-universal.jar) 
	UCHIJ	JEI{2.28.6.173} [Just Enough Items] (jei_1.8.9-2.28.6.173.jar) 
	UCHIJ	BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-19.jar) 
	UCHIJ	bookshelfapi{2.3.4} [Bookshelf] (Bookshelf-API-1.8.9-2.3.4.jar) 
	UCHIJ	Botania{r1.8-249} [Botania] (Botania.r1.8-248-unofficial-0.6.2.jar) 
	UCHIJ	BuildCraft|Core{7.2.0-pre12} [BuildCraft] (buildcraft-7.2.0-pre12.jar) 
	UCHIJ	BuildCraft|Transport{7.2.0-pre12} [BC Transport] (buildcraft-7.2.0-pre12.jar) 
	UCHIJ	BuildCraft|Builders{7.2.0-pre12} [BC Builders] (buildcraft-7.2.0-pre12.jar) 
	UCHIJ	BuildCraft|Compat{7.2.0-pre12-compat1} [BuildCraft Compat] (buildcraft-7.2.0-pre12-compat1.jar) 
	UCHIJ	BuildCraft|Energy{7.2.0-pre12} [BC Energy] (buildcraft-7.2.0-pre12.jar) 
	UCHIJ	BuildCraft|Factory{7.2.0-pre12} [BC Factory] (buildcraft-7.2.0-pre12.jar) 
	UCHIJ	BuildCraft|Silicon{7.2.0-pre12} [BC Silicon] (buildcraft-7.2.0-pre12.jar) 
	UCHIJ	BuildCraft|Robotics{7.2.0-pre12} [BC Robotics] (buildcraft-7.2.0-pre12.jar) 
	UCHIJ	cfmce{1.0} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0-mc1.8.9.jar) 
	UCHIJ	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCHIJ	ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
	UCHIJ	cosmeticarmorreworked{1.8.9-v2c} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v2c.jar) 
	UCHIJ	craftingtweaks{3.0.52} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.52.jar) 
	UCHIJ	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
	UCHIJ	lootablebodies{1.4.0} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.4.0.jar) 
	UCHIJ	cyclopscore{0.5.0} [Cyclops Core] (CyclopsCore-1.8.9-0.5.0.jar) 
	UCHIJ	spawn_defuzzer{1.1.0} [Spawn Defuzzer] (defuzz-1.2.0.jar) 
	UCHIJ	DummyCore{2.2.189.0.} [DummyCore] (DummyCore-2.2.189.0.jar) 
	UCHIJ	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.6.jar) 
	UCHIJ	FFS{1.8.9-1.4.5.7.91} [Fancy Fluid Storage] (Fancy Fluid Storage-1.8.9-1.4.5.7.91.jar) 
	UCHIJ	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJ	fluidconverters{2.0.0} [FluidConverters] (FluidConverters-1.8.9-2.0.0.jar) 
	UCHIJ	advgenerators{0.9.19.4} [Advanced Generators] (generators-0.9.19.4-mc1.8.9.jar) 
	UCHIJ	HelpFixer{1.8.9-1.2.12} [HelpFixer] (HelpFixer-1.8.9-1.2.12.jar) 
	UCHIJ	hgp{Release} [Horizontal Glass Panes] (hgp-1.8.9-1.0.2.jar) 
	UCHIJ	inventorytweaks{1.60-beta-38-b8950ce} [Inventory Tweaks] (InventoryTweaks-1.60-beta-38.jar) 
	UCHIJ	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJ	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCHIJ	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJ	k4lib{1.8.9-1.0.14} [K4Lib] (k4lib-1.8.9-1.0.14-universal.jar) 
	UCHIJ	llor{1.0.5-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.5-mc1.8.9.jar) 
	UCHIJ	malisiscore{1.8.9-2.0.1} [MalisisCore] (malisiscore-1.8.9-2.0.1.jar) 
	UCHIJ	malisisdoors{1.8.9-3.0.1} [MalisisDoors] (malisisdoors-1.8.9-3.0.1.jar) 
	UCHIJ	mantle{1.8.9-0.8.2.jenkins95} [Mantle] (Mantle-1.8.9-0.8.2.jar) 
	UCHIJ	mcmultipart{1.0.6} [MCMultiPart] (MCMultiPart-1.0.6-universal.jar) 
	UCHIJ	MC{4.5} [MedicineCraft] (MedicineCraft V5.3 1.8.9.jar) 
	UCHIJ	MineMenu{1.3.0} [MineMenu] (MineMenu-1.8.9-1.3.0.B45-universal.jar) 
	UCHIJ	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHIJ	ModNameTooltip{1.0.0} [Mod Name Tooltip] (modnametooltip_1.8.8-1.0.0.jar) 
	UCHIJ	moreplayermodels{1.8.9} [MorePlayerModels] (MorePlayerModels_1.8.9(27feb16).jar) 
	UCHIJ	cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6.1(1.8.9).jar) 
	UCHIJ	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.1-3.jar) 
	UCHIJ	tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct] (TConstruct-1.8.9-2.1.0.jar) 
	UCHIJ	neotech{2.3.9} [NeoTech] (NeoTech-1.8.9-2.3.9.jar) 
	UCHIJ	recipehandler{0.3} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.8.X).jar) 
	UCHIJ	fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
	UCHIJ	simplerecipes{1.8.9a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.8.9a.jar) 
	UCHIJ	parachutemod{1.2.2} [Parachute Mod] (parachutemod-ng-1.8.9-1.2.2-341.jar) 
	UCHIJ	PassthroughSigns{1.0.2} [Passthrough Signs] (PassthroughSigns-1.8.X-1.0.2.B4.jar) 
	UCHIJ	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCHIJ	RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
	UCHIJ	RandomThings{3.6.4} [Random Things] (RandomThings-MC1.8.9-3.6.4.jar) 
	UCHIJ	reborncore{1.4.3.20} [RebornCore] (RebornCore-1.8.9-1.4.3.20-universal.jar) 
	UCHIJ	RecipeTooltips{1.1.24} [RecipeTooltips] (RecipeTooltips-1.8.9-1.1.24.jar) 
	UCHIJ	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UCHIJ	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
	UCHIJ	rftools{4.22beta28} [RFTools] (rftools-1.8.9-4.22beta28.jar) 
	UCHIJ	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UCHIJ	ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.8.8.jar) 
	UCHIJ	routerreborn{1.8.9-3.0.4} [RouterReborn] (RouterReborn-1.8.9-3.0.4-universal.jar) 
	UCHIE	RTG{0.0.1} [Realistic Terrain Generation] (RTG-1.8.9-0.0.1.jar) 
	UCHIJ	ShetiPhianCore{3.1.0} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.0.jar) 
	UCHIJ	SimpleDimensions{1.2} [Simple Dimensions] (SimpleDimensions-1.2.jar) 
	UCHIJ	simpleretrogen{2.2.2+3} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.2+3.jar) 
	UCHIJ	spawnercraft{1.8.9-2.3} [SpawnerCraft] (SpawnerCraft2-1.8.9-2.3.jar) 
	UCHIJ	StorageDrawers{1.8.9-2.4.2} [Storage Drawers] (StorageDrawers-1.8.9-2.4.2.jar) 
	UCHIJ	thaumicbases{2.1.189.32} [Thaumic Bases] (ThaumicBases-2.1.189.32.jar) 
	UCHIJ	thaumicinfusion{4.82} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.82.jar) 
	UCHIJ	thutcore{2.3.0} [ThutCore] (thutcore-2.3.0.jar) 
	Loaded coremods (and transformers): 
thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.6.4.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
MalisisCorePlugin (malisiscore-1.8.9-2.0.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.4.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  DummyCore.ASM.DCASMManager
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.1001' Renderer: 'AMD Radeon HD 7900 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	List of loaded APIs: 
		* AppleCoreAPI (2.0.0) from AppleCore-mc1.8.9-1.3.0.jar
		* Baubles|API (1.1.1.0) from Baubles-1.8.9-1.1.3.0.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.8.9-2.0.0-19.jar
		* BotaniaAPI (76) from Botania.r1.8-248-unofficial-0.6.2.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|core (2.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.2.0-pre12.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.2.0-pre12.jar
		* CoFHAPI (1.8.9R1.2.0B1) from mcjtylib-1.8.9-1.8.1beta7.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from RebornCore-1.8.9-1.4.3.20-universal.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
		* ComputerCraft|API (1.78) from ComputerCraft1.78.jar
		* ComputerCraft|API|FileSystem (1.78) from ComputerCraft1.78.jar
		* ComputerCraft|API|Lua (1.78) from ComputerCraft1.78.jar
		* ComputerCraft|API|Media (1.78) from ComputerCraft1.78.jar
		* ComputerCraft|API|Peripheral (1.78) from ComputerCraft1.78.jar
		* ComputerCraft|API|Permissions (1.78) from ComputerCraft1.78.jar
		* ComputerCraft|API|Redstone (1.78) from ComputerCraft1.78.jar
		* ComputerCraft|API|Turtle (1.78) from ComputerCraft1.78.jar
		* CraftingTweaks|API (4.1) from craftingtweaks-mc1.8.9-3.0.52.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.6.173.jar
		* McJtyLib (1.8.9-1.8.1beta7) from mcjtylib-1.8.9-1.8.1beta7.jar
		* reborncoreAPI (1.4.3.20) from RebornCore-1.8.9-1.4.3.20-universal.jar
		* SecurityCraftAPI (1.1) from [1.8.8] SecurityCraft v1.8.1.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.2.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.2.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.2.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.2.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.2.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.2.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.2.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.2.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.2.jar
		* Thaumaturgical Knowledge|API (0.2) from 1.8.9 - Thaumaturgical Knowledge-0.2.jar
		* Thaumcraft|API (5.1.2.0) from Thaumcraft-1.8.9-5.1.6.jar
		* thut|API (1.0.0) from thutcore-2.3.0.jar
	[DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''DummyCore''Thaumic Infusion'
	OptiFine Version: OptiFine_1.8.9_HD_U_H4
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13416 Compatibility Profile Context 15.300.1025.1001
	OpenGlRenderer: AMD Radeon HD 7900 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8
```

**Comment by srs-bsns** [comment]
Upgrade BoP to the latest build for 1.8.9 and try again, please.: [BiomesOPlenty-1.8.9-3.0.0.1924-universal.jar](http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/BiomesOPlenty/1.8.9-3.0.0.1924/BiomesOPlenty-1.8.9-3.0.0.1924-universal.jar)

There were changes made to the Flower Island biome since the build that you are using (1896) and there was also a change made in the latest build to make BoP more compatible with RTG.

**Comment by zacklmoore** [comment]
That fixed it, thanks!

**Comment by whichonespink44** [comment]
@topisani Might be worth updating the minimum required version of BOP in [mcmod.info](https://github.com/Team-RTG/1.8.9-Realistic-Terrain-Generation/blob/master/src/main/resources/mcmod.info#L20) to prevent MC from loading if a user has an incompatible version.

I tried to do it myself this morning, but couldn't compile 1.8.9 source... think my gradle got confused or something.

**Comment by topisani** [comment]
ill do that!
